name: Deploy to Krystal

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

      - name: Prepare standalone deployment
        run: |
          cp -r .next/static .next/standalone/.next/static
          if [ -d "public" ]; then cp -r public .next/standalone/public; fi
          date -u +"%Y-%m-%dT%H:%M:%SZ" > .next/standalone/deploy-marker.txt

      - name: Deploy to Krystal via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.KRYSTAL_HOST }}
          username: ${{ secrets.KRYSTAL_USER }}
          password: ${{ secrets.KRYSTAL_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./.next/standalone/
          server-dir: ${{ secrets.FTP_REMOTE_DIR }}/
          log-level: verbose
          dangerous-clean-slate: true
